{{- if and .Values.dmnGateway.enabled .Values.dmnGateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestration-dmn-chart.fullname" . | default .Release.Name }}-dmn-gateway
  labels:
    app.kubernetes.io/name: dmn-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.dmnGateway.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.dmnGateway.ingress.className }}
  ingressClassName: {{ .Values.dmnGateway.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.dmnGateway.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "orchestration-dmn-chart.fullname" $ | default $.Release.Name }}-dmn-gateway
                port:
                  number: {{ $.Values.dmnGateway.service.port | default 80 }}
          {{- end }}
    {{- end }}
  {{- if .Values.dmnGateway.ingress.tls }}
  tls:
    {{- toYaml .Values.dmnGateway.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
