apiVersion: v1
kind: Service
metadata:
  name: orchestration-dmn
spec:
  type: {{ .Values.service.type }}
  selector:
    app: orchestration-dmn
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
