apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestration-dmn
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/<org>/<repo>.git'
    targetRevision: main
    path: orchestration-dmn-chart

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orchestration

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
